### ISSUE TITLE
Docker-compse up之后celery报错

### ISSUE THREAD

**Issue by bobmayuze** [twtrubiks/docker-django-celery-tutorial#2]
`
app_1       | /usr/local/lib/python3.6/site-packages/celery/platforms.py:795: RuntimeWarning: You're running the worker with superuser privileges: this is
app_1       | absolutely not recommended!
app_1       | 
app_1       | Please specify a different user using the -u option.
app_1       | 
app_1       | User information: uid=0 euid=0 gid=0 egid=0
app_1       | 
app_1       |   uid=uid, euid=euid, gid=gid, egid=egid,
app_1       | Traceback (most recent call last):
app_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 123, in __getattr__
app_1       |     return self[key]
app_1       | KeyError: 'async'
app_1       | 
app_1       | During handling of the above exception, another exception occurred:
app_1       | 
app_1       | Traceback (most recent call last):
app_1       |   File "/usr/local/bin/celery", line 11, in <module>
app_1       |     sys.exit(main())
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
app_1       |     _main()
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
app_1       |     cmd.execute_from_commandline(argv)
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
app_1       |     super(CeleryCommand, self).execute_from_commandline(argv)))
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
app_1       |     return self.handle_argv(self.prog_name, argv[1:])
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
app_1       |     return self.execute(command, argv)
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
app_1       |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
app_1       |     return self(*args, **options)
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
app_1       |     ret = self.run(*args, **kwargs)
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
app_1       |     **kwargs)
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 99, in __init__
app_1       |     self.setup_instance(**self.prepare_args(**kwargs))
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 122, in setup_instance
app_1       |     self.should_use_eventloop() if use_eventloop is None
app_1       |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
app_1       |     self._conninfo.transport.implements.async and
app_1       |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 125, in __getattr__
app_1       |     raise AttributeError(key)
app_1       | AttributeError: async

`

感觉应该是没有specify user的问题 大家在运行的时候有报错嘛＝－＝

**Comment by bobmayuze** [comment]
修复方案可以参考[这里](https://github.com/celery/kombu/issues/870)

具体是在requirements中加上
`
kombu==4.1.0
`

BTW 非常感谢你的教程

---来自大陆的网友

**Comment by twtrubiks** [comment]
@bobmayuze  自己當初寫這篇教學文的時候沒遇到這個問題，不過非常謝謝您的解答。

**Comment by ppkliu** [comment]
celery==4.2.0 改成这样好像就好了！ Ubuntu 20.04

**Comment by twtrubiks** [comment]
> celery==4.2.0 改成这样好像就好了！ Ubuntu 20.04

謝謝回報
